// Package all imports all the commands
package all

import (
	// Active commands
	_ "github.com/rmdashrf/rclone_acd_hack/cmd"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/authorize"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/cat"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/check"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/cleanup"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/cmount"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/config"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/copy"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/copyto"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/cryptcheck"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/dedupe"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/delete"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/genautocomplete"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/gendocs"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/listremotes"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/ls"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/lsd"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/lsl"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/md5sum"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/memtest"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/mkdir"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/mount"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/move"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/moveto"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/obscure"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/purge"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/rmdir"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/rmdirs"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/sha1sum"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/size"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/sync"
	_ "github.com/rmdashrf/rclone_acd_hack/cmd/version"
)
